name: CI
on:
  push:
    branches: [ main ]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      options: '--network=host'
    steps:
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)
      - name: Setup node
        uses: actions/setup-node@v4
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: npm install
        run: 'npm i'
      - name: Unit test
        run: 'npm run test:unit'
      - name: Unit test
        run: 'npm run build'
  cypress-e2e:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-20.14.0-chrome-126.0.6478.114-1-ff-127.0.1-edge-126.0.2592.61-1
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm start
          browser: chrome